export const SERVER_ERROR_CODE = 500;
export const BAD_REQUEST_ERROR_CODE = 400;
export const UNAUTHORIZED_REQUEST_ERROR_CODE = 401;
export const MALFORMED_REQUEST_ERROR_CODE = 1000;
export const QUERY_ERROR_CODE = 1001;
export const AUTH_ERROR_CODE = 1002;
export const UNAUTHORIZED_ERROR_CODE = 1003;
